openapi: 3.0.0
info:
  title: Dummy API
  version: 1.0.0

paths:
  /hello:
    post:
      summary: Returns a greeting
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HelloRequest'
      responses:
        "200":
          description: Successful greeting
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'
  /getDevilsAdvocate:
    post:
      summary: Returns a qna pair object
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DevilsAdvocateRequest'
      responses:
        "200":
          description: Successful qna pair
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DevilsAdvocateResponse'
  /getComparisonData:
    post:
      summary: Returns a comparison object
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ComparisonDataRequest'
      responses:
        "200":
          description: Successful comparison object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComparisonDataResponse'
  /chat:
    post:
      summary: Returns a chat response
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        "200":
          description: Successful chat response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse' 
                

components:
  schemas:
    HelloRequest:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    HelloResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    DevilsAdvocateRequest:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    DevilsAdvocateResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    ComparisonDataRequest:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    ComparisonDataResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    ChatRequest:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    ChatResponse:
      type: object
      properties:
        reply:
          type: string
      required:
        - reply

